<?php

namespace AppBundle\Repository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function add($form, $row)
    {
        $flush = $this->save($form, $row);         
    }
    public function edit($form, $row)
    {
        $flush = $this->save($form, $row);
    }
    public function save($form, $row)
    {
        $em = $this->getEntityManager();
        
        $row->setApellidos($form->get('apellidos')->getData());
		$row->setNombre($form->get('nombre')->getData());
		$row->setEdad($form->get('edad')->getData());
		$row->setDireccion($form->get('direccion')->getData());
		$row->setTelefono($form->get('telefono')->getData());

        $em->persist($row);
        $em->flush();        
    }
    public function delete($row)
    {
        $em = $this->getEntityManager();
        $em->remove($row);
        $em->flush();      
    }
}
